# INDEX REQUEST
GET http://localhost:3000/products.json


### SHOW REQUEST
GET http://localhost:3000/products/11.json


### ADD PRODUCTS
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test3",
  "price": 169,
  "image_url": "https://images.ctfassets.net/od02wyo8cgm5/1G8iYG3NZFlrBEjKjosALZ/49b52061bef11f6a533f17d1e46b0981/cloudstratus_2-fw21-lake_flare-m-g1.png?w=500&h=500&fl=progressive&q=61&bg=rgb:f7f7f7&fm=jpg",
  "description": "test teeeeeesssssstttt"
}

### PRODUCTS UPDATE

PATCH http://localhost:3000/products/11.json
Content-Type: application/json

{
  "price": 165
}

### PRODUCTS DELETE
DELETE http://localhost:3000/products/10.json

### SUPPLIER REQUESTS ###

# SHOW SUPPLIER INDEX
GET http://localhost:3000/suppliers.json
Content-Type: application/json

### CREATE SUPPLIER
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "supplier3",
  "email": "s3@suppliers.com",
  "phone_number": "234232324",
  "supplier_id": "4"
}

### UPDATE SUPPLIER
PUT http://localhost:3000/suppliers/1
Content-Type: application/json

{
  "name": "supplier1",
  "email": "supplier1@suppliers.com"
}


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Mavi",
  "email": "mavi@test.com",
  "password": "food",
  "password_confirmation": "food"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

# {
#   "email": "test@test.com",
#   "password": "password"
# }

{
  "email": "mavi@test.com",
  "password": "food"
}
### ORDER CREATE
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1Mjk4OTV9.OZPNrEYL7PIrY_l--R3B8q2wIq2XZP5UTqEpXjbefdo


### ORDER SHOW
GET http://localhost:3000/orders/10.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1Mjk4OTV9.OZPNrEYL7PIrY_l--R3B8q2wIq2XZP5UTqEpXjbefdo

### ORDER INDEX
GET http://localhost:3000/orders.json
Content-Type: application/json

### Carted_Product Create
POST http://localhost:3000/carted_products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1Mjk4OTV9.OZPNrEYL7PIrY_l--R3B8q2wIq2XZP5UTqEpXjbefdo

{
  "product_id": 7,
  "quantity": 20
}

### CartedProduct Index
GET http://localhost:3000/carted_products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1Mjk4OTV9.OZPNrEYL7PIrY_l--R3B8q2wIq2XZP5UTqEpXjbefdo

### Carted Product Remove
DELETE http://localhost:3000/carted_products/4.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzU1MzU3MjZ9.SOT-AVSkfu7lKzI3Fj-qPyRD24g8jH3vLHnjqSHX7DE